[package]
name = "model"
version = "0.1.0"
edition = "2021"

[dependencies]
anna = { path = "../anna" }
entity = { path = "../orm/entity" }
anyhow = "1.0.86"
serde = { version = "1.0.204", features = ["derive"] }
serde_bytes = "0.11.15"
serde_json = "1.0.122"
sha2 = "0.10.8"
utoipa = { version = "4.2.3", features = ["axum_extras"] }
