[package]
name = "infra"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
aes-gcm = "0.10.3"
async-trait = "0.1.81"
base32 = "0.5.1"
base64 = "0.22.1"
chrono = "0.4.38"
dashmap = "6"
jsonwebtoken = "9.3.0"
regex = "1.10.6"
reqwest = { version = "0.12.5", default-features = false, features = ["charset", "http2", "macos-system-configuration", "cookies", "json", "multipart", "rustls-tls", "gzip", "brotli"] }
rss = "2.0.8"
scraper = "0.20.0"
serde_bencode = "0.2.4"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
sha1 = "0.10.6"
sha2 = "0.10.8"
sqlx = { version = "0.8.3", features = ["sqlite", "runtime-tokio-rustls"] }
tokio = { version = "1.39.2", features = ["fs", "sync", "time", "rt"] }
tracing = "0.1.40"
uuid = { version = "1.10.0", features = ["v4"] }
futures-executor = "0.3"
domain = { path = "../domain" }
anime = { path = "../anime" }
feed = { path = "../feed" }
user = { path = "../user" }
rule = { path = "../rule" }
subscription = { path = "../subscription" }
space = { path = "../space" }

[dev-dependencies]
service = { path = "../service" }
tempfile = "3.19.1"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread", "fs", "sync", "time"] }
