//! 真实抓取一次后硬编码的来源数据夹具（禁止手工造假）。
//!
//! - `SEASONAL_JSON`：`BgmClient`（bangumi-data + TMDB）抓取的当季条目，2026-10-02 抓取。
//! - `NYAA_FEED`：`https://nyaa.si/?page=rss` 的真实 RSS 解析结果（`{:#?}` 输出 + `String` 字段补 `to_string()`）。
#![allow(dead_code)]

use anime::entity::model::AnimeMetadata;
use feed::entity::model::{FeedData, FeedItem};

/// 抓取时间：2026-10-02，来源 `AnimeSeasonalProvider::get()`（bgm + TMDB）。
pub const SEASONAL_JSON: &str = r####"[
  {
    "series_metadata": {
      "origin_name": "転生したら剣でした",
      "cn_name": "转生成为魔剑",
      "desc": "一回神，我发现自己已经转生至异世界了。不是作为普通人类，而是一把剑。再往周围环顾，原来这里是个魔物猖獗，险象环生的草原地带。觉得性命受到威胁的主角，运用让自己身体飘浮的能力，逐步猎杀魔物。就在这时，主角为了休息而插进地面的瞬间，能力居然破功，动弹不得。然而就无计可施的主角面前，突如其来出现一名奴隶打扮的猫耳少女...",
      "air_date": "2022-10-05",
      "genres": [
        "动画",
        "喜剧",
        "Sci-Fi & Fantasy"
      ]
    },
    "external_link": [
      {
        "id": {
          "Int": 412008
        },
        "target": "Bangumi",
        "type": "tv"
      },
      {
        "id": {
          "Int": 134667
        },
        "target": "TMDB",
        "type": "tv"
      }
    ],
    "titles": [
      {
        "name": "轉生就是劍 第二季",
        "match_name": "轉生就是劍第二季",
        "target": "ZhTw",
        "origin": false
      },
      {
        "name": "Reincarnated as a Sword Season 2",
        "match_name": "reincarnatedasaswordseason2",
        "target": "EN",
        "origin": false
      },
      {
        "name": "转生成为魔剑 第二季",
        "match_name": "转生成为魔剑第二季",
        "target": "ZhCn",
        "origin": false
      },
      {
        "name": "转生就是剑 第二季",
        "match_name": "转生就是剑第二季",
        "target": "ZhCn",
        "origin": false
      },
      {
        "name": "转生成为魔剑了 第二季",
        "match_name": "转生成为魔剑了第二季",
        "target": "ZhCn",
        "origin": false
      },
      {
        "name": "転生したら剣でしたII",
        "match_name": "転生したら剣でしたii",
        "target": "JP",
        "origin": true
      },
      {
        "name": "Reencarnado como una espada",
        "match_name": "reencarnadocomounaespada",
        "target": {
          "Other": "cl"
        },
        "origin": false
      },
      {
        "name": "转生就是剑",
        "match_name": "转生就是剑",
        "target": "ZhCn",
        "origin": false
      },
      {
        "name": "我转生成剑之后发生的事",
        "match_name": "我转生成剑之后发生的事",
        "target": "ZhCn",
        "origin": false
      },
      {
        "name": "轉生成为魔剑",
        "match_name": "轉生成为魔剑",
        "target": "ZhCn",
        "origin": false
      },
      {
        "name": "转生成为魔剑",
        "match_name": "转生成为魔剑",
        "target": "ZhCn",
        "origin": false
      },
      {
        "name": "Reencarné como una espada",
        "match_name": "reencarnécomounaespada",
        "target": {
          "Other": "es"
        },
        "origin": false
      },
      {
        "name": "Tensei Shitara Ken Deshita",
        "match_name": "tenseishitarakendeshita",
        "target": "JP",
        "origin": false
      },
      {
        "name": "Tenken",
        "match_name": "tenken",
        "target": "JP",
        "origin": false
      },
      {
        "name": "전생검",
        "match_name": "전생검",
        "target": "KR",
        "origin": false
      },
      {
        "name": "I Became the Sword by Transmigrating",
        "match_name": "ibecametheswordbytransmigrating",
        "target": "EN",
        "origin": false
      }
    ],
    "air_weekday": "Wednesday",
    "air_date": "2026-10-07",
    "air_quarter": 202610,
    "season": [
      {
        "target": "Bangumi",
        "lang": "JP",
        "desc": "原本作为无名奴隶遭受虐待的黑猫族少女芙兰，遇到拥有智慧的剑，拜他为师，并成为他的装备者。加入冒险者公会的芙兰，在完成多个任务的过程中，逐渐提升声望。为了追求强大的终点「进化」，芙兰不断努力，渴望帮她实现愿望的师父，将下一个目的地定为了港口都市达兹。师父和芙兰在前往该处的途中，发现「浮游岛」，并遇到目标攻陷浮游岛的死灵术师让·杜比。两人接受他的委托，和他一起挑战浮游岛的迷宫，但那里竟然是死灵魔兽蠢蠢欲动的凶恶迷宫！猫耳少女和爱女心切的魔剑的新冒险，即将开始！\r\n\r\n\r\n\r\n[简介原文]\r\n「名無し」の奴隷として虐げられていた黒猫族の少女フランは、「知性を持つ武器」である剣――師匠と出会い、その装備者となった。\r\n城砦都市アレッサの冒険者ギルドに所属したフランは、数々のクエストをこなしながら冒険者として名を上げていく。\r\n強さの果てにある「進化」を目指すフラン。彼女の「願い」を叶えたい師匠は、次なる目的地を港町ダーズと定めた。\r\nその道中、天空に浮かぶ「浮遊島」を発見した師匠とフランは、浮遊島の完全攻略を目指す死霊術師ジャン・ドゥービーと出会う。彼の依頼を受け、ともに浮遊島の迷宮に挑むことになるのだが……。\r\nそこは死霊魔獣が蠢く凶悪な迷宮だった！\r\n猫耳少女と親バカな剣の新たな冒険が始まる!!",
        "season": 2,
        "eps": [
          {
            "ep": 1,
            "sort": 1.0,
            "air_date": "2026-10-07",
            "title": [
              {
                "name": "空に浮かんでるのは島でした",
                "match_name": "空に浮かんでるのは島でした",
                "target": "JP",
                "origin": true
              },
              {
                "name": "浮在空中的是岛",
                "match_name": "浮在空中的是岛",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 1420,
            "desc": "前往港都达兹的师父和芙兰，在途中接近偶然发现的浮游岛，却遭到骷髅骑士攻击，狼狈坠落。坠落后，两人遇见了死灵术师让·杜比。\r\n\r\n港町ダーズを目指す師匠とフランは、道中で発見した浮遊島に接近する。\r\nしかし骸骨騎士に迎撃され、あえなく墜落。\r\n落下した先で、死霊術師ジャン・ドゥービーに出会う。\r\n\r\n脚本：永野たかひろ　\r\n絵コンテ：石平信司　\r\n演出：清水一伸\r\n総作画監督：齋藤温子　\r\n作画監督：森出 剛、たなべようこ、渡邉光稀、滝澤 陸",
            "ex_id": {
              "Int": 1738646
            }
          },
          {
            "ep": 2,
            "sort": 2.0,
            "air_date": "2026-10-14",
            "title": [
              {
                "name": "ジャン·ドゥービーは優秀でした",
                "match_name": "ジャンドゥービーは優秀でした",
                "target": "JP",
                "origin": true
              },
              {
                "name": "让·杜比很优秀",
                "match_name": "让杜比很优秀",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 0,
            "desc": "",
            "ex_id": {
              "Int": 1738647
            }
          }
        ],
        "planned_episode_count": 12
      },
      {
        "target": "TMDB",
        "lang": "ZhCn",
        "desc": "",
        "season": 2,
        "eps": [
          {
            "ep": 1,
            "sort": 1.0,
            "air_date": "2026-10-08",
            "title": [
              {
                "name": "浮在空中的是岛",
                "match_name": "浮在空中的是岛",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 0,
            "desc": "",
            "ex_id": {
              "Int": 5798627
            }
          },
          {
            "ep": 2,
            "sort": 2.0,
            "air_date": "2026-10-15",
            "title": [
              {
                "name": "让·杜比很优秀",
                "match_name": "让杜比很优秀",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 0,
            "desc": "",
            "ex_id": {
              "Int": 7894795
            }
          },
          {
            "ep": 3,
            "sort": 3.0,
            "air_date": "2026-10-22",
            "title": [
              {
                "name": "第 3 集",
                "match_name": "第3集",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 0,
            "desc": "",
            "ex_id": {
              "Int": 7894797
            }
          },
          {
            "ep": 4,
            "sort": 4.0,
            "air_date": "2026-10-29",
            "title": [
              {
                "name": "第 4 集",
                "match_name": "第4集",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 0,
            "desc": "",
            "ex_id": {
              "Int": 7894799
            }
          },
          {
            "ep": 5,
            "sort": 5.0,
            "air_date": "2026-11-05",
            "title": [
              {
                "name": "第 5 集",
                "match_name": "第5集",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 0,
            "desc": "",
            "ex_id": {
              "Int": 7894801
            }
          },
          {
            "ep": 6,
            "sort": 6.0,
            "air_date": "2026-11-12",
            "title": [
              {
                "name": "第 6 集",
                "match_name": "第6集",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 0,
            "desc": "",
            "ex_id": {
              "Int": 7894802
            }
          },
          {
            "ep": 7,
            "sort": 7.0,
            "air_date": "2026-11-19",
            "title": [
              {
                "name": "第 7 集",
                "match_name": "第7集",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 0,
            "desc": "",
            "ex_id": {
              "Int": 7894803
            }
          },
          {
            "ep": 8,
            "sort": 8.0,
            "air_date": "2026-11-26",
            "title": [
              {
                "name": "第 8 集",
                "match_name": "第8集",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 0,
            "desc": "",
            "ex_id": {
              "Int": 7894805
            }
          },
          {
            "ep": 9,
            "sort": 9.0,
            "air_date": "2026-12-03",
            "title": [
              {
                "name": "第 9 集",
                "match_name": "第9集",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 0,
            "desc": "",
            "ex_id": {
              "Int": 7894806
            }
          },
          {
            "ep": 10,
            "sort": 10.0,
            "air_date": "2026-12-10",
            "title": [
              {
                "name": "第 10 集",
                "match_name": "第10集",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 0,
            "desc": "",
            "ex_id": {
              "Int": 7894807
            }
          },
          {
            "ep": 11,
            "sort": 11.0,
            "air_date": "2026-12-17",
            "title": [
              {
                "name": "第 11 集",
                "match_name": "第11集",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 0,
            "desc": "",
            "ex_id": {
              "Int": 7894809
            }
          },
          {
            "ep": 12,
            "sort": 12.0,
            "air_date": "2026-12-24",
            "title": [
              {
                "name": "第 12 集",
                "match_name": "第12集",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 0,
            "desc": "",
            "ex_id": {
              "Int": 7894810
            }
          }
        ],
        "planned_episode_count": 12
      }
    ]
  },
  {
    "series_metadata": {
      "origin_name": "獣王武神ダンデヴァイン",
      "cn_name": "獣王武神ダンデヴァイン",
      "desc": "",
      "air_date": "2026-10-07",
      "genres": [
        "动画",
        "Sci-Fi & Fantasy",
        "动作冒险"
      ]
    },
    "external_link": [
      {
        "id": {
          "Int": 657778
        },
        "target": "Bangumi",
        "type": "tv"
      },
      {
        "id": {
          "Int": 323937
        },
        "target": "TMDB",
        "type": "tv"
      }
    ],
    "titles": [
      {
        "name": "獸王武神丹帝拜恩",
        "match_name": "獸王武神丹帝拜恩",
        "target": "ZhTw",
        "origin": false
      },
      {
        "name": "兽王武神丹帝拜恩",
        "match_name": "兽王武神丹帝拜恩",
        "target": "ZhCn",
        "origin": false
      },
      {
        "name": "兽王武神DANDIVINE",
        "match_name": "兽王武神dandivine",
        "target": "ZhCn",
        "origin": false
      },
      {
        "name": "獣王武神ダンデヴァイン",
        "match_name": "獣王武神ダンデヴァイン",
        "target": "JP",
        "origin": true
      },
      {
        "name": "Gattaishin Series",
        "match_name": "gattaishinseries",
        "target": "JP",
        "origin": false
      },
      {
        "name": "The God of Combined Series",
        "match_name": "thegodofcombinedseries",
        "target": "JP",
        "origin": false
      },
      {
        "name": "Jyu-Oh Mujin Dandivine",
        "match_name": "jyuohmujindandivine",
        "target": "JP",
        "origin": false
      },
      {
        "name": "合体神シリーズ",
        "match_name": "合体神シリーズ",
        "target": "JP",
        "origin": false
      },
      {
        "name": "Jyuō Mujin Dandevuain",
        "match_name": "jyuōmujindandevuain",
        "target": "JP",
        "origin": false
      },
      {
        "name": "Beast King Warrior God Dandivine",
        "match_name": "beastkingwarriorgoddandivine",
        "target": "EN",
        "origin": false
      }
    ],
    "air_weekday": "Wednesday",
    "air_date": "2026-10-07",
    "air_quarter": 202610,
    "season": [
      {
        "target": "Bangumi",
        "lang": "JP",
        "desc": "自从合体机器人「丹帝拜恩」击败了神秘敌人「暗波斯多」后，已经过了20年。\r\n世界一片和平，然而过去将丹帝拜恩制成玩具风靡一时的「玩具制造商凯斯加」，却也因过度依赖丹帝拜恩，导致公司营运状况每况愈下。凯斯加社长「静寂弦十郎」因此盼望，即便搅乱和平，也要让丹帝拜恩复活。\r\n也许是上天听见了他的愿望，暗波斯多再次现身于东京。20年来无忧无虑、耽溺于和平的人们突然陷入了恐慌之中。正当所有人仓皇逃跑时，过去曾是主要驾驶员的叔叔「黑田勇作」，引领着高中生「静寂戟刃」坐进了丹帝拜恩。\r\n究竟，\r\n再次现身的暗波斯多，他究竟有什么目的？\r\n凯斯加会再次称霸玩具业界吗？\r\n全新的战斗即将揭开序幕！\r\n\r\n\r\n\r\n[简介原文]\r\n『合体神シリーズ』\r\n“今こそ合体ロボットに熱い息吹を！”\r\n胸を熱くする合体ロボットの文化を未来に繋げるため、ホビーレーベル『メカスマ』とロボットを愛するクリエイターが集結。 企画段階から玩具とアニメーションを完全連動させる、新たなマーチャンダイジングを展開いたします。\r\n\r\n「合体神シリーズ」第一弾\r\nTVアニメ『獣王武神ダンデヴァイン』\r\n\r\n■あらすじ\r\n合体ロボット「ダンデヴァイン」が謎の敵「アポスドール」を撃退して20年。\r\n世界は平和だったが、ダンデヴァインの玩具化で⼀世を⾵靡した「おもちゃメーカー・キャスガ」はダンデヴァインに依存し過ぎの結果、経営悪化の⼀途をたどりつつあった。\r\n平和を乱してでもダンデヴァインの復活を願うキャスガ社⻑の「静寂弦⼗郎（しじまげんじゅうろう）」。そんな彼の願望が天に届いたか、再び東京にアポスドールが現れる。\r\n20年間何事もなく平和に浸りきった⼈々は⼤パニックに陥る。\r\n皆が逃げ惑う中、かつてメインパイロットだった叔⽗「⿊岩勇作（くろいわゆうさく）」に誘われ、ダンデヴァインに乗り込む⾼校⽣「静寂戟刃（しじまげきは）」。\r\n\r\n果たして、新たに現れたアポスドールの⽬的は何なのか︖\r\nキャスガは再び玩具業界の覇権を⼿にするのか︖\r\n新たなる戦いが幕を開ける︕",
        "season": 1,
        "eps": [],
        "planned_episode_count": 12
      },
      {
        "target": "TMDB",
        "lang": "ZhCn",
        "desc": "",
        "season": 1,
        "eps": [
          {
            "ep": 1,
            "sort": 1.0,
            "air_date": "2026-10-07",
            "title": [
              {
                "name": "第 1 集",
                "match_name": "第1集",
                "target": "ZhCn",
                "origin": false
              }
            ],
            "duration_seconds": 0,
            "desc": "",
            "ex_id": {
              "Int": 7321288
            }
          }
        ],
        "planned_episode_count": 1
      }
    ]
  }
]"####;

/// 抓取时间：2026-10-02，真实站点 RSS：<https://nyaa.si/?page=rss>。
pub const NYAA_URL: &str = "https://nyaa.si/?page=rss";

pub fn seasonal() -> Vec<AnimeMetadata> {
    serde_json::from_str(SEASONAL_JSON).expect("captured seasonal json must parse")
}

pub fn nyaa_feed() -> FeedData {
FeedData {
    source_key: "d4740a133fefda70d02b1c39becf83e0675b2a9e".to_string(),
    items: vec![
        FeedItem {
            title: "A New Dawn BD Remux".to_string(),
            source_url: "https://nyaa.si/view/2168590".to_string(),
            resource_url: "https://nyaa.si/download/2168590.torrent".to_string(),
            published_at: 1790931354,
            info_hash: [
                184,
                143,
                175,
                159,
                213,
                56,
                7,
                138,
                151,
                173,
                32,
                18,
                236,
                210,
                127,
                222,
                112,
                67,
                30,
                84,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 트릭컬 만화동산 - 01 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168588".to_string(),
            resource_url: "https://nyaa.si/download/2168588.torrent".to_string(),
            published_at: 1790931226,
            info_hash: [
                209,
                142,
                61,
                68,
                145,
                221,
                174,
                227,
                51,
                204,
                35,
                120,
                110,
                162,
                100,
                193,
                234,
                194,
                37,
                204,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 전생했더니 검이었습니다 Ⅱ - 01 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168586".to_string(),
            resource_url: "https://nyaa.si/download/2168586.torrent".to_string(),
            published_at: 1790931044,
            info_hash: [
                196,
                108,
                121,
                171,
                223,
                130,
                93,
                74,
                162,
                224,
                115,
                77,
                15,
                90,
                51,
                71,
                210,
                73,
                15,
                11,
            ],
        },
        FeedItem {
            title: "[Doomdos] - LINK CLICK 3 - 第09话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168585".to_string(),
            resource_url: "https://nyaa.si/download/2168585.torrent".to_string(),
            published_at: 1790931036,
            info_hash: [
                28,
                75,
                53,
                62,
                2,
                83,
                72,
                137,
                146,
                2,
                84,
                192,
                188,
                62,
                204,
                212,
                53,
                43,
                43,
                91,
            ],
        },
        FeedItem {
            title: "[綠茶字幕組] FX戰士久留美 / FX Senshi Kurumi-chan [01v2][WebRip][1080p][繁日內嵌]".to_string(),
            source_url: "https://nyaa.si/view/2168584".to_string(),
            resource_url: "https://nyaa.si/download/2168584.torrent".to_string(),
            published_at: 1790930026,
            info_hash: [
                115,
                210,
                1,
                76,
                246,
                82,
                44,
                251,
                159,
                55,
                46,
                236,
                79,
                168,
                237,
                136,
                144,
                118,
                220,
                60,
            ],
        },
        FeedItem {
            title: "[绿茶字幕组] FX战士久留美 / FX Senshi Kurumi-chan [01v2][WebRip][1080p][简日内嵌]".to_string(),
            source_url: "https://nyaa.si/view/2168583".to_string(),
            resource_url: "https://nyaa.si/download/2168583.torrent".to_string(),
            published_at: 1790930018,
            info_hash: [
                140,
                103,
                200,
                142,
                148,
                72,
                28,
                56,
                172,
                35,
                2,
                183,
                79,
                101,
                83,
                73,
                55,
                220,
                26,
                229,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 신 테니스의 왕자 U-17 WORLD CUP 결승 멤버 결정전 - 01 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168582".to_string(),
            resource_url: "https://nyaa.si/download/2168582.torrent".to_string(),
            published_at: 1790929330,
            info_hash: [
                21,
                230,
                184,
                67,
                14,
                28,
                227,
                146,
                183,
                211,
                255,
                79,
                46,
                243,
                145,
                23,
                191,
                189,
                249,
                209,
            ],
        },
        FeedItem {
            title: "[ToonsHub] JoJos Bizarre Adventure S06E03 1080p NF WEB-DL MULTi AAC2.0 H.264 (JoJo no Kimyou na Bouken: Steel Ball Run - 2nd - 3rd STAGE, Multi-Audio, Multi-Subs)".to_string(),
            source_url: "https://nyaa.si/view/2168581".to_string(),
            resource_url: "https://nyaa.si/download/2168581.torrent".to_string(),
            published_at: 1790928853,
            info_hash: [
                233,
                214,
                127,
                46,
                39,
                214,
                32,
                17,
                91,
                113,
                123,
                162,
                177,
                113,
                234,
                77,
                163,
                22,
                51,
                96,
            ],
        },
        FeedItem {
            title: "[Doomdos] - FX 전사 쿠루미 - 01 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168580".to_string(),
            resource_url: "https://nyaa.si/download/2168580.torrent".to_string(),
            published_at: 1790928840,
            info_hash: [
                31,
                61,
                220,
                116,
                137,
                106,
                22,
                15,
                174,
                6,
                17,
                113,
                46,
                185,
                218,
                214,
                126,
                68,
                77,
                62,
            ],
        },
        FeedItem {
            title: "JoJos Bizarre Adventure 2012 S06E03 MULTi AD 1080p NF WEB-DL AAC2.0 x264-Tsundere-Raws (VF, FRENCH, SUBFRENCH, VOSTFR, JoJo's Bizarre Adventure Stardust Crusaders, Le Bizzarre Avventure di JoJo, SBR)".to_string(),
            source_url: "https://nyaa.si/view/2168579".to_string(),
            resource_url: "https://nyaa.si/download/2168579.torrent".to_string(),
            published_at: 1790928464,
            info_hash: [
                210,
                59,
                22,
                191,
                162,
                41,
                190,
                120,
                109,
                99,
                211,
                227,
                69,
                130,
                65,
                142,
                83,
                136,
                33,
                89,
            ],
        },
        FeedItem {
            title: "JoJos Bizarre Adventure 2012 S06E03 MULTi AD 1080p NF WEB-DL AAC2.0 H.265-Tsundere-Raws (VF, FRENCH, SUBFRENCH, VOSTFR, JoJo's Bizarre Adventure Stardust Crusaders, Le Bizzarre Avventure di JoJo, SBR)".to_string(),
            source_url: "https://nyaa.si/view/2168578".to_string(),
            resource_url: "https://nyaa.si/download/2168578.torrent".to_string(),
            published_at: 1790928447,
            info_hash: [
                80,
                224,
                238,
                89,
                153,
                9,
                88,
                16,
                50,
                40,
                208,
                133,
                201,
                186,
                216,
                210,
                229,
                19,
                78,
                125,
            ],
        },
        FeedItem {
            title: "[Doomdos] - (더빙) 도굴왕 - 12 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168577".to_string(),
            resource_url: "https://nyaa.si/download/2168577.torrent".to_string(),
            published_at: 1790928437,
            info_hash: [
                90,
                236,
                52,
                186,
                109,
                87,
                139,
                255,
                49,
                56,
                184,
                1,
                219,
                95,
                171,
                24,
                164,
                254,
                132,
                22,
            ],
        },
        FeedItem {
            title: "JoJos Bizarre Adventure 2012 S06E03 MULTi AD 1080p NF WEB-DL AAC2.0 AV1-Tsundere-Raws (VF, FRENCH, SUBFRENCH, VOSTFR, JoJo's Bizarre Adventure Stardust Crusaders, JoJo's Bizarre Adventure Golden Wind)".to_string(),
            source_url: "https://nyaa.si/view/2168576".to_string(),
            resource_url: "https://nyaa.si/download/2168576.torrent".to_string(),
            published_at: 1790928433,
            info_hash: [
                246,
                120,
                95,
                193,
                39,
                23,
                160,
                109,
                107,
                30,
                144,
                59,
                218,
                138,
                193,
                82,
                57,
                33,
                44,
                84,
            ],
        },
        FeedItem {
            title: "[ToonsHub] JoJos Bizarre Adventure S06E03 1080p NF WEB-DL DUAL AAC2.0 H.264 (JoJo no Kimyou na Bouken: Steel Ball Run - 2nd - 3rd STAGE, Dual-Audio, Multi-Subs)".to_string(),
            source_url: "https://nyaa.si/view/2168575".to_string(),
            resource_url: "https://nyaa.si/download/2168575.torrent".to_string(),
            published_at: 1790928083,
            info_hash: [
                12,
                157,
                175,
                28,
                88,
                163,
                246,
                62,
                151,
                89,
                193,
                132,
                240,
                251,
                134,
                74,
                52,
                52,
                78,
                214,
            ],
        },
        FeedItem {
            title: "[绿茶字幕组] 无职转生 第三季 ～到了异世界就拿出真本事～ / Mushoku Tensei S3 [10][WebRip][1080p][简繁日内封]".to_string(),
            source_url: "https://nyaa.si/view/2168574".to_string(),
            resource_url: "https://nyaa.si/download/2168574.torrent".to_string(),
            published_at: 1790928025,
            info_hash: [
                55,
                198,
                197,
                78,
                142,
                71,
                201,
                42,
                74,
                122,
                90,
                17,
                199,
                229,
                157,
                26,
                182,
                228,
                102,
                224,
            ],
        },
        FeedItem {
            title: "[绿茶字幕组] 无职转生 第三季 ～到了异世界就拿出真本事～ / Mushoku Tensei S3 [11][WebRip][1080p][简繁日内封]".to_string(),
            source_url: "https://nyaa.si/view/2168573".to_string(),
            resource_url: "https://nyaa.si/download/2168573.torrent".to_string(),
            published_at: 1790928016,
            info_hash: [
                86,
                9,
                27,
                188,
                43,
                5,
                75,
                186,
                24,
                171,
                129,
                86,
                188,
                95,
                253,
                81,
                74,
                50,
                191,
                214,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 담배 고양이 - 08 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168572".to_string(),
            resource_url: "https://nyaa.si/download/2168572.torrent".to_string(),
            published_at: 1790927789,
            info_hash: [
                207,
                31,
                160,
                61,
                153,
                194,
                125,
                81,
                40,
                109,
                11,
                138,
                137,
                102,
                18,
                1,
                235,
                63,
                89,
                173,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 클레바테스 Ⅱ -마수왕과 가짜 용사 전승- - 13 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168571".to_string(),
            resource_url: "https://nyaa.si/download/2168571.torrent".to_string(),
            published_at: 1790927334,
            info_hash: [
                178,
                225,
                149,
                182,
                116,
                238,
                35,
                176,
                44,
                109,
                131,
                219,
                224,
                83,
                26,
                3,
                17,
                163,
                236,
                237,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 정반대의 너와 나 2기 - 24 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168570".to_string(),
            resource_url: "https://nyaa.si/download/2168570.torrent".to_string(),
            published_at: 1790926562,
            info_hash: [
                155,
                164,
                190,
                91,
                15,
                65,
                9,
                106,
                33,
                109,
                91,
                194,
                190,
                6,
                205,
                23,
                34,
                214,
                191,
                169,
            ],
        },
        FeedItem {
            title: "[Shridhuu][1080p HBR] Renegade Immortal Movie 2 Battle of the Immortal Slayer / 仙逆剧场版 弑仙之战 / Xian Ni Movie: Shi Xian Zhi Zhan".to_string(),
            source_url: "https://nyaa.si/view/2168569".to_string(),
            resource_url: "https://nyaa.si/download/2168569.torrent".to_string(),
            published_at: 1790926297,
            info_hash: [
                125,
                74,
                115,
                22,
                91,
                232,
                206,
                198,
                75,
                66,
                28,
                137,
                102,
                163,
                216,
                82,
                49,
                123,
                225,
                74,
            ],
        },
        FeedItem {
            title: "[Shridhuu][4K] Renegade Immortal Movie 2 Battle of the Immortal Slayer / 仙逆剧场版 弑仙之战 / Xian Ni Movie: Shi Xian Zhi Zhan".to_string(),
            source_url: "https://nyaa.si/view/2168568".to_string(),
            resource_url: "https://nyaa.si/download/2168568.torrent".to_string(),
            published_at: 1790926242,
            info_hash: [
                122,
                147,
                17,
                102,
                43,
                60,
                149,
                82,
                64,
                99,
                204,
                190,
                206,
                190,
                138,
                46,
                127,
                207,
                141,
                145,
            ],
        },
        FeedItem {
            title: "[ToonsHub] Tokyo Revengers S04E01 REPACK 1080p HULU WEB-DL DUAL AAC2.0 H.264 (Tokyo Revengers: Santen Sensou-hen, Dual-Audio, Multi-Subs)".to_string(),
            source_url: "https://nyaa.si/view/2168567".to_string(),
            resource_url: "https://nyaa.si/download/2168567.torrent".to_string(),
            published_at: 1790926228,
            info_hash: [
                233,
                128,
                219,
                241,
                162,
                244,
                107,
                223,
                123,
                183,
                179,
                172,
                19,
                141,
                19,
                65,
                141,
                110,
                9,
                72,
            ],
        },
        FeedItem {
            title: "メンタル激強保健医の力技カウンセリング 第01-03巻 [Mental Geki Kyo Hoken I No Chikara Waza Counseling vol 01-03]".to_string(),
            source_url: "https://nyaa.si/view/2168566".to_string(),
            resource_url: "https://nyaa.si/download/2168566.torrent".to_string(),
            published_at: 1790925936,
            info_hash: [
                128,
                101,
                244,
                15,
                88,
                89,
                72,
                231,
                183,
                199,
                178,
                140,
                149,
                90,
                212,
                244,
                20,
                199,
                132,
                39,
            ],
        },
        FeedItem {
            title: "[ZeroReverse] False Memory - S01E05 (WEBRip 1080p x265 10-bit EAC-3)".to_string(),
            source_url: "https://nyaa.si/view/2168565".to_string(),
            resource_url: "https://nyaa.si/download/2168565.torrent".to_string(),
            published_at: 1790925730,
            info_hash: [
                243,
                70,
                61,
                25,
                253,
                170,
                23,
                61,
                130,
                211,
                178,
                125,
                30,
                13,
                254,
                56,
                1,
                237,
                39,
                75,
            ],
        },
        FeedItem {
            title: "【TSDM字幕组】[虽然我是不完美恶女 ～雏宫蝶鼠替换传～][07][MKV][WebRip][HEVC-10bit 1080p AAC][简日内封字幕][Futsutsuka na Akujo dewa Gozaimasu ga][ふつつかな悪女ではございますが ～雛宮蝶鼠とりかえ伝～]".to_string(),
            source_url: "https://nyaa.si/view/2168562".to_string(),
            resource_url: "https://nyaa.si/download/2168562.torrent".to_string(),
            published_at: 1790924618,
            info_hash: [
                193,
                245,
                88,
                164,
                212,
                180,
                246,
                214,
                55,
                237,
                121,
                190,
                63,
                198,
                44,
                173,
                245,
                104,
                49,
                165,
            ],
        },
        FeedItem {
            title: "【TSDM字幕组】[虽然我是不完美恶女 ～雏宫蝶鼠替换传～][07][MKV][WebRip][AV1-10bit 1080p AAC][简日内封字幕][Futsutsuka na Akujo dewa Gozaimasu ga][ふつつかな悪女ではございますが ～雛宮蝶鼠とりかえ伝～]".to_string(),
            source_url: "https://nyaa.si/view/2168561".to_string(),
            resource_url: "https://nyaa.si/download/2168561.torrent".to_string(),
            published_at: 1790924569,
            info_hash: [
                36,
                34,
                10,
                187,
                38,
                188,
                152,
                209,
                193,
                255,
                70,
                154,
                10,
                37,
                178,
                222,
                8,
                229,
                100,
                89,
            ],
        },
        FeedItem {
            title: "【TSDM字幕组】[虽然我是不完美恶女 ～雏宫蝶鼠替换传～][07][GB][1080P][MP4][简日双语内嵌][Futsutsuka na Akujo dewa Gozaimasu ga][ふつつかな悪女ではございますが ～雛宮蝶鼠とりかえ伝～]".to_string(),
            source_url: "https://nyaa.si/view/2168560".to_string(),
            resource_url: "https://nyaa.si/download/2168560.torrent".to_string(),
            published_at: 1790924488,
            info_hash: [
                132,
                194,
                10,
                100,
                75,
                179,
                156,
                209,
                79,
                59,
                117,
                180,
                130,
                123,
                246,
                4,
                118,
                33,
                137,
                14,
            ],
        },
        FeedItem {
            title: "【TSDM字幕组】[恶女不才，请多关照 ～雏宫蝶鼠换身传～][06][MKV][WebRip][HEVC-10bit 1080p AAC][简日双语内封][Futsutsuka na Akujo de wa Gozaimasu ga: Suuguu Chouso Torikae Den][ふつつかな悪女ではございますが ～雛宮蝶鼠とりかえ伝～]".to_string(),
            source_url: "https://nyaa.si/view/2168559".to_string(),
            resource_url: "https://nyaa.si/download/2168559.torrent".to_string(),
            published_at: 1790923921,
            info_hash: [
                216,
                6,
                112,
                26,
                203,
                157,
                120,
                96,
                122,
                95,
                45,
                130,
                104,
                200,
                77,
                38,
                206,
                177,
                175,
                96,
            ],
        },
        FeedItem {
            title: "Eun-sil-i |  The Dearest (DVD 480p)".to_string(),
            source_url: "https://nyaa.si/view/2168558".to_string(),
            resource_url: "https://nyaa.si/download/2168558.torrent".to_string(),
            published_at: 1790923868,
            info_hash: [
                183,
                219,
                197,
                53,
                234,
                91,
                14,
                102,
                225,
                252,
                229,
                84,
                174,
                7,
                178,
                137,
                114,
                20,
                85,
                84,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 무직전생 Ⅲ ~이세계에 갔으면 최선을 다한다~ - 14 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168557".to_string(),
            resource_url: "https://nyaa.si/download/2168557.torrent".to_string(),
            published_at: 1790923855,
            info_hash: [
                128,
                47,
                131,
                161,
                44,
                59,
                60,
                179,
                70,
                251,
                100,
                194,
                163,
                203,
                146,
                197,
                191,
                152,
                185,
                158,
            ],
        },
        FeedItem {
            title: "【TSDM字幕组】[恶女不才，请多关照 ～雏宫蝶鼠换身传～][06][MKV][WebRip][AV1 10bit 1080p AAC][简日双语内封][Futsutsuka na Akujo de wa Gozaimasu ga: Suuguu Chouso Torikae Den][ふつつかな悪女ではございますが ～雛宮蝶鼠とりかえ伝～]".to_string(),
            source_url: "https://nyaa.si/view/2168555".to_string(),
            resource_url: "https://nyaa.si/download/2168555.torrent".to_string(),
            published_at: 1790923778,
            info_hash: [
                36,
                249,
                237,
                29,
                217,
                80,
                109,
                21,
                47,
                253,
                160,
                168,
                165,
                125,
                150,
                151,
                156,
                197,
                41,
                140,
            ],
        },
        FeedItem {
            title: "[Kotobuki] Tsuihou Sareta Tensei Juu Kishi wa Game Chishiki de Musou Suru 14 [1080p HEVC Multisub] | The Exiled Heavy Knight Knows How to Game the System".to_string(),
            source_url: "https://nyaa.si/view/2168554".to_string(),
            resource_url: "https://nyaa.si/download/2168554.torrent".to_string(),
            published_at: 1790923302,
            info_hash: [
                11,
                246,
                64,
                206,
                91,
                183,
                133,
                28,
                90,
                128,
                0,
                185,
                12,
                147,
                27,
                59,
                105,
                55,
                82,
                153,
            ],
        },
        FeedItem {
            title: "[Doomdos] - (자막) 도굴왕 - 12 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168553".to_string(),
            resource_url: "https://nyaa.si/download/2168553.torrent".to_string(),
            published_at: 1790923235,
            info_hash: [
                106,
                36,
                127,
                242,
                112,
                182,
                84,
                111,
                123,
                214,
                22,
                205,
                1,
                111,
                206,
                172,
                60,
                44,
                151,
                143,
            ],
        },
        FeedItem {
            title: "【TSDM字幕组】[虽然我是不完美恶女 ～雏宫蝶鼠替换传～][06][GB][1080P][MP4][简日双语内嵌][Futsutsuka na Akujo dewa Gozaimasu ga][ふつつかな悪女ではございますが ～雛宮蝶鼠とりかえ伝～]".to_string(),
            source_url: "https://nyaa.si/view/2168552".to_string(),
            resource_url: "https://nyaa.si/download/2168552.torrent".to_string(),
            published_at: 1790923190,
            info_hash: [
                89,
                254,
                36,
                180,
                239,
                16,
                242,
                237,
                228,
                95,
                144,
                230,
                108,
                137,
                84,
                19,
                178,
                109,
                46,
                69,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 투명한 밤을 달리는 너와, 눈에 보이지 않는 사랑을 했다. - 10 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168551".to_string(),
            resource_url: "https://nyaa.si/download/2168551.torrent".to_string(),
            published_at: 1790922612,
            info_hash: [
                248,
                185,
                102,
                87,
                140,
                176,
                246,
                219,
                100,
                249,
                42,
                45,
                137,
                119,
                63,
                214,
                74,
                255,
                39,
                26,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 네가 죽을 때까지 사랑하고 싶어 - 12 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168550".to_string(),
            resource_url: "https://nyaa.si/download/2168550.torrent".to_string(),
            published_at: 1790921919,
            info_hash: [
                24,
                161,
                170,
                245,
                160,
                44,
                204,
                79,
                178,
                184,
                144,
                131,
                124,
                120,
                49,
                85,
                175,
                37,
                39,
                8,
            ],
        },
        FeedItem {
            title: "[ToonsHub] LINK CLICK S04E09 1080p CR WEB-DL AAC2.0 H.264 (Shiguang Dailiren, Multi-Subs)".to_string(),
            source_url: "https://nyaa.si/view/2168549".to_string(),
            resource_url: "https://nyaa.si/download/2168549.torrent".to_string(),
            published_at: 1790918940,
            info_hash: [
                195,
                14,
                84,
                20,
                124,
                21,
                35,
                229,
                104,
                235,
                163,
                69,
                175,
                121,
                70,
                170,
                129,
                97,
                235,
                167,
            ],
        },
        FeedItem {
            title: "姉と弟がまぁまぁ仲良く暮らす日常。 第01巻 [Ane to Ototo Ga Ma Ma Nakayoku Kurasu Nichijo vol 01]".to_string(),
            source_url: "https://nyaa.si/view/2168548".to_string(),
            resource_url: "https://nyaa.si/download/2168548.torrent".to_string(),
            published_at: 1790918531,
            info_hash: [
                143,
                19,
                228,
                223,
                253,
                122,
                80,
                133,
                213,
                106,
                21,
                94,
                223,
                92,
                223,
                61,
                42,
                116,
                255,
                226,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 신수 유치원 - 11 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168547".to_string(),
            resource_url: "https://nyaa.si/download/2168547.torrent".to_string(),
            published_at: 1790917980,
            info_hash: [
                45,
                97,
                137,
                150,
                250,
                95,
                193,
                109,
                5,
                52,
                197,
                40,
                190,
                252,
                104,
                202,
                209,
                5,
                100,
                165,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 성하체통 시즌 2 - 23 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168546".to_string(),
            resource_url: "https://nyaa.si/download/2168546.torrent".to_string(),
            published_at: 1790917288,
            info_hash: [
                12,
                39,
                91,
                245,
                222,
                81,
                254,
                40,
                47,
                224,
                106,
                60,
                185,
                132,
                70,
                193,
                62,
                212,
                254,
                11,
            ],
        },
        FeedItem {
            title: "[Doomdos] - Re _ 제로부터 시작하는 이세계 생활 4기 - 19 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168545".to_string(),
            resource_url: "https://nyaa.si/download/2168545.torrent".to_string(),
            published_at: 1790916730,
            info_hash: [
                144,
                65,
                74,
                206,
                37,
                53,
                181,
                16,
                138,
                90,
                86,
                36,
                67,
                216,
                130,
                158,
                207,
                73,
                164,
                163,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 라이어 게임 - 24 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168544".to_string(),
            resource_url: "https://nyaa.si/download/2168544.torrent".to_string(),
            published_at: 1790915741,
            info_hash: [
                185,
                239,
                163,
                31,
                237,
                182,
                107,
                179,
                122,
                17,
                122,
                13,
                240,
                115,
                252,
                197,
                228,
                37,
                118,
                13,
            ],
        },
        FeedItem {
            title: "[Doomdos] - The Exiled Heavy Knight Knows How to Game the System - 第14话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168543".to_string(),
            resource_url: "https://nyaa.si/download/2168543.torrent".to_string(),
            published_at: 1790915582,
            info_hash: [
                141,
                19,
                12,
                180,
                3,
                249,
                210,
                162,
                148,
                150,
                141,
                16,
                101,
                254,
                45,
                146,
                186,
                129,
                2,
                224,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 여신 「이세계 전생하면 뭐가 되고 싶습니까」 나「용사의 갈비뼈로」 - 12 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168542".to_string(),
            resource_url: "https://nyaa.si/download/2168542.torrent".to_string(),
            published_at: 1790915365,
            info_hash: [
                14,
                193,
                98,
                74,
                129,
                116,
                235,
                149,
                34,
                214,
                12,
                164,
                225,
                170,
                189,
                134,
                163,
                128,
                80,
                39,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 雪王来了！ - 第17话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168540".to_string(),
            resource_url: "https://nyaa.si/download/2168540.torrent".to_string(),
            published_at: 1790914940,
            info_hash: [
                63,
                108,
                160,
                163,
                158,
                217,
                247,
                43,
                218,
                81,
                153,
                173,
                41,
                238,
                220,
                98,
                171,
                134,
                212,
                170,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 缔灵爱水心缠 - 第10话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168539".to_string(),
            resource_url: "https://nyaa.si/download/2168539.torrent".to_string(),
            published_at: 1790914846,
            info_hash: [
                241,
                101,
                238,
                24,
                199,
                14,
                131,
                178,
                48,
                241,
                64,
                99,
                176,
                56,
                67,
                42,
                197,
                186,
                71,
                165,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 苏东坡与杭州的故事 - 第33话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168538".to_string(),
            resource_url: "https://nyaa.si/download/2168538.torrent".to_string(),
            published_at: 1790914429,
            info_hash: [
                179,
                236,
                38,
                159,
                169,
                232,
                103,
                79,
                158,
                62,
                42,
                59,
                31,
                194,
                140,
                233,
                111,
                165,
                190,
                90,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 검은 고양이와 마녀의 교실 - 20 [1080P LFTLNET WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168537".to_string(),
            resource_url: "https://nyaa.si/download/2168537.torrent".to_string(),
            published_at: 1790914350,
            info_hash: [
                108,
                250,
                79,
                25,
                157,
                167,
                160,
                180,
                135,
                79,
                255,
                69,
                10,
                164,
                103,
                46,
                168,
                10,
                230,
                148,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 掌门低调点 - 第33话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168536".to_string(),
            resource_url: "https://nyaa.si/download/2168536.torrent".to_string(),
            published_at: 1790914224,
            info_hash: [
                90,
                24,
                90,
                128,
                88,
                17,
                226,
                211,
                33,
                224,
                226,
                62,
                174,
                12,
                210,
                226,
                54,
                179,
                55,
                231,
            ],
        },
        FeedItem {
            title: "[Doomdos] - 时光代理人 第三季 - 第9话（超大抢先）话 - [4K BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168535".to_string(),
            resource_url: "https://nyaa.si/download/2168535.torrent".to_string(),
            published_at: 1790914080,
            info_hash: [
                79,
                73,
                65,
                8,
                242,
                232,
                208,
                106,
                109,
                75,
                109,
                117,
                44,
                166,
                209,
                203,
                222,
                243,
                8,
                193,
            ],
        },
        FeedItem {
            title: "[Feibanyama] Tomb Raider King S01E12 [CR WebRip 1080p H265 Veryslow AAC Multi-Subs] (Dogulwang)".to_string(),
            source_url: "https://nyaa.si/view/2168534".to_string(),
            resource_url: "https://nyaa.si/download/2168534.torrent".to_string(),
            published_at: 1790913883,
            info_hash: [
                120,
                108,
                236,
                97,
                101,
                88,
                59,
                121,
                101,
                248,
                172,
                164,
                178,
                178,
                86,
                254,
                184,
                206,
                67,
                217,
            ],
        },
        FeedItem {
            title: "Beyblade X - Episode 125 [English Dub][720p]".to_string(),
            source_url: "https://nyaa.si/view/2168532".to_string(),
            resource_url: "https://nyaa.si/download/2168532.torrent".to_string(),
            published_at: 1790913736,
            info_hash: [
                8,
                105,
                7,
                122,
                202,
                66,
                58,
                41,
                204,
                186,
                213,
                220,
                179,
                164,
                82,
                153,
                247,
                213,
                114,
                189,
            ],
        },
        FeedItem {
            title: "The Chiral Night fall into Slow Damage".to_string(),
            source_url: "https://nyaa.si/view/2168531".to_string(),
            resource_url: "https://nyaa.si/download/2168531.torrent".to_string(),
            published_at: 1790913540,
            info_hash: [
                205,
                141,
                17,
                173,
                169,
                112,
                252,
                127,
                123,
                33,
                4,
                156,
                104,
                141,
                94,
                23,
                240,
                184,
                231,
                36,
            ],
        },
        FeedItem {
            title: "[Bizmillah] FX Senshi Kurumi-chan - 01 (1080p)".to_string(),
            source_url: "https://nyaa.si/view/2168530".to_string(),
            resource_url: "https://nyaa.si/download/2168530.torrent".to_string(),
            published_at: 1790913383,
            info_hash: [
                34,
                25,
                47,
                250,
                215,
                173,
                96,
                193,
                170,
                243,
                182,
                241,
                246,
                253,
                21,
                247,
                66,
                185,
                111,
                206,
            ],
        },
        FeedItem {
            title: "[Doomdos] - Mushoku Tensei: Jobless Reincarnation Season 3 - 第11话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168529".to_string(),
            resource_url: "https://nyaa.si/download/2168529.torrent".to_string(),
            published_at: 1790913063,
            info_hash: [
                14,
                173,
                27,
                230,
                40,
                206,
                106,
                171,
                57,
                68,
                68,
                176,
                195,
                129,
                254,
                60,
                107,
                180,
                245,
                39,
            ],
        },
        FeedItem {
            title: "[Doomdos] - Mushoku Tensei: Jobless Reincarnation Season 3 - 第10话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168528".to_string(),
            resource_url: "https://nyaa.si/download/2168528.torrent".to_string(),
            published_at: 1790912778,
            info_hash: [
                226,
                163,
                100,
                248,
                35,
                74,
                212,
                133,
                73,
                114,
                197,
                186,
                107,
                234,
                149,
                198,
                145,
                114,
                73,
                112,
            ],
        },
        FeedItem {
            title: "[ASW] Link Click S3 - 09 [1080p HEVC x265 10Bit][AAC]".to_string(),
            source_url: "https://nyaa.si/view/2168527".to_string(),
            resource_url: "https://nyaa.si/download/2168527.torrent".to_string(),
            published_at: 1790912679,
            info_hash: [
                106,
                28,
                190,
                64,
                115,
                141,
                93,
                35,
                135,
                64,
                24,
                158,
                103,
                54,
                8,
                85,
                11,
                247,
                204,
                212,
            ],
        },
        FeedItem {
            title: "[Doomdos] - Mushoku Tensei: Jobless Reincarnation Season 3 - 第09话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168526".to_string(),
            resource_url: "https://nyaa.si/download/2168526.torrent".to_string(),
            published_at: 1790912468,
            info_hash: [
                231,
                170,
                66,
                168,
                182,
                69,
                105,
                172,
                130,
                79,
                194,
                224,
                50,
                121,
                65,
                124,
                49,
                201,
                130,
                198,
            ],
        },
        FeedItem {
            title: "[Doomdos] - Mushoku Tensei: Jobless Reincarnation Season 3 - 第08话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168525".to_string(),
            resource_url: "https://nyaa.si/download/2168525.torrent".to_string(),
            published_at: 1790912323,
            info_hash: [
                6,
                183,
                69,
                207,
                190,
                12,
                55,
                111,
                71,
                218,
                248,
                159,
                243,
                166,
                94,
                126,
                186,
                47,
                232,
                12,
            ],
        },
        FeedItem {
            title: "[Doomdos] - Mushoku Tensei: Jobless Reincarnation Season 3 - 第07话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168524".to_string(),
            resource_url: "https://nyaa.si/download/2168524.torrent".to_string(),
            published_at: 1790912156,
            info_hash: [
                230,
                110,
                200,
                246,
                202,
                241,
                33,
                206,
                142,
                25,
                233,
                184,
                130,
                49,
                246,
                58,
                100,
                114,
                161,
                220,
            ],
        },
        FeedItem {
            title: "[Doomdos] - Mushoku Tensei: Jobless Reincarnation Season 3 - 第06话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168523".to_string(),
            resource_url: "https://nyaa.si/download/2168523.torrent".to_string(),
            published_at: 1790911856,
            info_hash: [
                159,
                48,
                45,
                41,
                86,
                20,
                54,
                155,
                28,
                5,
                80,
                166,
                27,
                80,
                29,
                39,
                10,
                118,
                200,
                84,
            ],
        },
        FeedItem {
            title: "[Doomdos] - Mushoku Tensei: Jobless Reincarnation Season 3 - 第05话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168522".to_string(),
            resource_url: "https://nyaa.si/download/2168522.torrent".to_string(),
            published_at: 1790911644,
            info_hash: [
                227,
                220,
                189,
                79,
                174,
                186,
                169,
                255,
                103,
                48,
                104,
                65,
                194,
                234,
                84,
                240,
                198,
                192,
                203,
                234,
            ],
        },
        FeedItem {
            title: "[绿茶字幕组] FX战士久留美 / FX Senshi Kurumi-chan [01][WebRip][1080p][简日内嵌]".to_string(),
            source_url: "https://nyaa.si/view/2168521".to_string(),
            resource_url: "https://nyaa.si/download/2168521.torrent".to_string(),
            published_at: 1790911541,
            info_hash: [
                46,
                105,
                94,
                28,
                11,
                244,
                238,
                61,
                168,
                154,
                56,
                160,
                20,
                240,
                45,
                226,
                221,
                3,
                69,
                119,
            ],
        },
        FeedItem {
            title: "キラーシッター 第01巻 [Killer Sitter vol 01]".to_string(),
            source_url: "https://nyaa.si/view/2168520".to_string(),
            resource_url: "https://nyaa.si/download/2168520.torrent".to_string(),
            published_at: 1790911521,
            info_hash: [
                163,
                208,
                39,
                227,
                24,
                50,
                77,
                84,
                173,
                33,
                28,
                214,
                244,
                22,
                63,
                212,
                68,
                136,
                156,
                230,
            ],
        },
        FeedItem {
            title: "仮面夫婦 第01-04巻 [Kamen fufu vol 01-04]".to_string(),
            source_url: "https://nyaa.si/view/2168519".to_string(),
            resource_url: "https://nyaa.si/download/2168519.torrent".to_string(),
            published_at: 1790911487,
            info_hash: [
                248,
                161,
                240,
                210,
                223,
                59,
                44,
                238,
                188,
                94,
                43,
                98,
                82,
                224,
                224,
                102,
                131,
                13,
                129,
                13,
            ],
        },
        FeedItem {
            title: "[Doomdos] - Mushoku Tensei: Jobless Reincarnation Season 3 - 第04话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168518".to_string(),
            resource_url: "https://nyaa.si/download/2168518.torrent".to_string(),
            published_at: 1790911381,
            info_hash: [
                110,
                246,
                247,
                151,
                187,
                217,
                146,
                208,
                162,
                62,
                145,
                107,
                78,
                192,
                114,
                109,
                43,
                201,
                114,
                81,
            ],
        },
        FeedItem {
            title: "[Doomdos] - Mushoku Tensei: Jobless Reincarnation Season 3 - 第03话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168516".to_string(),
            resource_url: "https://nyaa.si/download/2168516.torrent".to_string(),
            published_at: 1790911205,
            info_hash: [
                151,
                83,
                228,
                44,
                145,
                121,
                231,
                169,
                173,
                122,
                201,
                135,
                55,
                99,
                15,
                131,
                6,
                13,
                128,
                68,
            ],
        },
        FeedItem {
            title: "[Doomdos] - Mushoku Tensei: Jobless Reincarnation Season 3 - 第02话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168515".to_string(),
            resource_url: "https://nyaa.si/download/2168515.torrent".to_string(),
            published_at: 1790911046,
            info_hash: [
                118,
                108,
                113,
                32,
                105,
                176,
                22,
                239,
                245,
                236,
                87,
                107,
                87,
                143,
                124,
                180,
                99,
                184,
                101,
                178,
            ],
        },
        FeedItem {
            title: "[Doomdos] - Mushoku Tensei: Jobless Reincarnation Season 3 - 第01话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168514".to_string(),
            resource_url: "https://nyaa.si/download/2168514.torrent".to_string(),
            published_at: 1790910859,
            info_hash: [
                143,
                238,
                102,
                134,
                8,
                137,
                87,
                208,
                2,
                13,
                138,
                170,
                133,
                27,
                42,
                48,
                240,
                21,
                22,
                255,
            ],
        },
        FeedItem {
            title: "[Doomdos] - The Frontier Lord Begins with Zero Subjects - 第12话 - [1080p BILIBILI COM WEB-DL]".to_string(),
            source_url: "https://nyaa.si/view/2168513".to_string(),
            resource_url: "https://nyaa.si/download/2168513.torrent".to_string(),
            published_at: 1790910665,
            info_hash: [
                1,
                33,
                57,
                7,
                217,
                130,
                154,
                240,
                71,
                135,
                161,
                237,
                198,
                181,
                82,
                130,
                102,
                226,
                78,
                210,
            ],
        },
        FeedItem {
            title: "[ToonsHub] LINK CLICK S04E06 1080p CR WEB-DL DUAL AAC2.0 H.264 (Shiguang Dailiren, Dual-Audio, Multi-Subs)".to_string(),
            source_url: "https://nyaa.si/view/2168512".to_string(),
            resource_url: "https://nyaa.si/download/2168512.torrent".to_string(),
            published_at: 1790910592,
            info_hash: [
                225,
                164,
                100,
                254,
                37,
                169,
                30,
                227,
                191,
                95,
                146,
                167,
                189,
                6,
                24,
                100,
                0,
                165,
                114,
                246,
            ],
        },
        FeedItem {
            title: "[AnoZu] Link Click S04E06 1080p CR WEB-DL Dual-Audio DDP 2.0 H.264 | Shiguang Dailiren III".to_string(),
            source_url: "https://nyaa.si/view/2168511".to_string(),
            resource_url: "https://nyaa.si/download/2168511.torrent".to_string(),
            published_at: 1790910558,
            info_hash: [
                127,
                207,
                218,
                48,
                55,
                161,
                0,
                126,
                251,
                178,
                17,
                242,
                10,
                69,
                18,
                251,
                123,
                79,
                189,
                109,
            ],
        },
    ],
}
}

/// 真实站点抓取结果中的种子条目（用于构造规则匹配用的资源）。
pub fn nyaa_item(title_contains: &str) -> FeedItem {
    nyaa_feed()
        .items
        .into_iter()
        .find(|i| i.title.contains(title_contains))
        .unwrap_or_else(|| panic!("captured nyaa feed has no item containing {title_contains}"))
}
